name: Makefile CI

on:
  push:
    tags:        
      - v*.**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create download dir
      run: mkdir -p downloads

    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'OA-WCVP/ipni-oa'
        version: 'latest'
        file: "ipni-oa-data.zip"
        target: 'downloads/ipni-oa-data.zip'
        token: ${{ secrets.PAT }}

    - name: Sanity check artifact download
      run: ls -ltra downloads

    - name: Install python dependencies
      run: pip install -r requirements.txt
      
    - name: Build charts and archive into a zip
      run: make archive
      
    - name: Release with built documents
      uses: softprops/action-gh-release@v1
      with:
        files: archive/map-charts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
          